"""add rich content fields to Program

Revision ID: 7f8d29810cf8
Revises: 87c098873bd7
Create Date: 2025-09-06 02:14:58.673608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8d29810cf8'
down_revision = '87c098873bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('intro_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('advantages_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_dates_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timeline_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('costs_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scholarships_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('savings_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('destination_md', sa.Text(), nullable=True))
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('destination_md')
        batch_op.drop_column('savings_md')
        batch_op.drop_column('scholarships_md')
        batch_op.drop_column('costs_md')
        batch_op.drop_column('timeline_md')
        batch_op.drop_column('key_dates_md')
        batch_op.drop_column('advantages_md')
        batch_op.drop_column('intro_md')
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
