"""add cover_image_url and summary to Program

Revision ID: 87c098873bd7
Revises: 9bda90edf69a
Create Date: 2025-09-05 20:14:48.924289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c098873bd7'
down_revision = '9bda90edf69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
