"""init tables: programs, requirements, student_profiles

Revision ID: 90cc73d48ab8
Revises: 
Create Date: 2025-08-08 00:44:18.558261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cc73d48ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('university', sa.String(length=160), nullable=True),
    sa.Column('degree_level', sa.String(length=80), nullable=True),
    sa.Column('discipline', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('start_terms', sa.String(length=120), nullable=True),
    sa.Column('tuition', sa.String(length=80), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('intro_image_url', sa.String(length=500), nullable=True),
    sa.Column('overview_md', sa.Text(), nullable=True),
    sa.Column('faq_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('program_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('req_type', sa.String(length=40), nullable=True),
    sa.Column('min_value', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('ielts', sa.Float(), nullable=True),
    sa.Column('toefl', sa.Float(), nullable=True),
    sa.Column('gre', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=120), nullable=True),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('work_years', sa.Float(), nullable=True),
    sa.Column('country_pref', sa.String(length=80), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('program')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('country', sa.VARCHAR(length=128), nullable=True),
    sa.Column('degree_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_profiles')
    op.drop_table('program_requirements')
    op.drop_table('programs')
    # ### end Alembic commands ###
