"""add case_studies and program stats endpoint

Revision ID: 9bda90edf69a
Revises: faf6ac11d7dd
Create Date: 2025-08-14 00:48:47.265212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bda90edf69a'
down_revision = 'faf6ac11d7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('student_alias', sa.String(length=80), nullable=True),
    sa.Column('target_university', sa.String(length=160), nullable=True),
    sa.Column('target_program', sa.String(length=160), nullable=True),
    sa.Column('outcome', sa.String(length=80), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_studies')
    # ### end Alembic commands ###
