"""program cn fields + overview_brief/image + highlights_md

Revision ID: a81608773d85
Revises: 7f8d29810cf8
Create Date: 2025-09-06 04:11:53.131818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81608773d85'
down_revision = '7f8d29810cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_cn', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('city_cn', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('university_cn', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('overview_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('overview_brief', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('highlights_md', sa.Text(), nullable=True))
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.drop_column('highlights_md')
        batch_op.drop_column('overview_brief')
        batch_op.drop_column('overview_image')
        batch_op.drop_column('university_cn')
        batch_op.drop_column('city_cn')
        batch_op.drop_column('country_cn')

    # ### end Alembic commands ###
