"""add product detail fields

Revision ID: d0bcd9b4f8d7
Revises: ad70c87d2fcb
Create Date: 2025-09-22 22:25:50.159356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bcd9b4f8d7'
down_revision = 'ad70c87d2fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('includes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('excludes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('faqs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('plans', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('detail_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_promise', sa.String(length=256), nullable=True))
        batch_op.create_index('idx_products_published_category', ['is_published', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_title'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index('idx_products_published_category')
        batch_op.drop_column('service_promise')
        batch_op.drop_column('detail_html')
        batch_op.drop_column('plans')
        batch_op.drop_column('faqs')
        batch_op.drop_column('steps')
        batch_op.drop_column('excludes')
        batch_op.drop_column('includes')
        batch_op.drop_column('highlights')
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
